# Generated by Django 5.0.1 on 2024-02-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_paymentmethod_shippingmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
