# Generated by Django 5.0.1 on 2024-02-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_shippingmethod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
