# Generated by Django 5.0.1 on 2024-02-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментария')),
                ('name', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('to_feed_back', models.BooleanField(default='False', verbose_name='К главному')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='homeapp.productmodel')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-date_add',),
            },
        ),
    ]
