# Generated by Django 5.0.1 on 2024-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_productmodel_slug_blogcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Check',
            field=models.CharField(default='healthy'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Country',
            field=models.CharField(default='uzb'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='MinWeight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='Quality',
            field=models.CharField(default='organic'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
