# Generated by Django 5.0.1 on 2024-02-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_productmodel_check_productmodel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables')], default='fruits', max_length=20, verbose_name='категория'),
        ),
    ]
