# Generated by Django 5.0.1 on 2024-02-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_featursmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='featursmodel',
            name='color2',
            field=models.CharField(default='service-content bg-primary text-center p-4 rounded', max_length=100),
        ),
    ]
