# Generated by Django 5.0.1 on 2024-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_featursmodel_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='featursmodel',
            name='text',
            field=models.CharField(default='text-white', max_length=100),
        ),
    ]
