# Generated by Django 5.0.1 on 2024-02-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_blogcomments_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='stars',
            field=models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=0, verbose_name='оценка'),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='stars',
            field=models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=0, verbose_name='оценка'),
        ),
    ]
